name: CI/CD workflow for Maven Build and Sonar Code scan
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        - name: Generate tests
        env:
            PYNGUIN_DANGER_AWARE: 1
        run: |
            chmod +x test_generation.sh
            ./test_generation.sh
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
        echo "PYTHONPATH set to: $(pwd)"
    - name: Clear previous coverage data
      run: |
        find . -name '.coverage' -delete
        find . -name 'coverage.xml' -delete
        echo "Cleared previous coverage data."
    - name: Run tests with 100% coverage
      run: |
        pytest -s --cov=testing_v1 --cov-report=xml --cov-fail-under=80
    # - name: Run Tests
    #   run: |
    #     pytest  # or `python -m unittest discover`
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
        projectBaseDir: .
        args: >
            -Dsonar.projectKey=Vipulpatel12_testing_unittest_f5155b76-70f8-4ceb-b37a-45b5a45cdd22
            -Dsonar.language=py
            -Dsonar.python.version=3.11
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
   
        